#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    timeout-minutes: 10
  strategy:
    matrix:
      node-version: [14.x, 16.x, 18.x, 20.x]
  steps:
  - uses: actions/checkout@v3
  - name: Clean global cache
    run: npm cache clean --force
  - name: Set up Node
    uses: ./
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'npm'
  - name: Install dependencies
    run: npm install
  - name: CI build & test
    run: |
      npm run build --if-present
      npm test
    env:
      CI: true
